### ISSUE TITLE
vipnode on windows dont find ipc 

### ISSUE THREAD

**Issue by heitorfm** [vipnode/vipnode#14]
Hi there,
I´m trying to run the vipnode on windows, but seens that its looking for the ipc in the wrong place.

> λ vipnode.exe
> client failed: no known transport for URL scheme "c"
>  -> Could not find the RPC path of the running Ethereum node (such as Geth or Parity). Tried "C:\Users\Heitor\AppData\Roaming\Ethereum\geth.ipc". Make sure your node is running with RPC enabled. You can specify the path with the --rpc="..." flag.

And when i try to pass the flag:
>unknown flag `rpc'

**Comment by shazow** [comment]
@heitorfm Can you share the full command you run when you try to supply the rpc flag?

**Comment by heitorfm** [comment]
With the 'client' flag the rpc paramenter works. But i also needed to pass the nodekey.

`λ vipnode.exe client --rpc=\\.\pipe\geth.ipc --nodekey=C:\Users\Heitor\ether-full\data-private\geth\nodekey`

The command ends up looking like that:
`λ vipnode.exe client --rpc=\\.\pipe\geth.ipc --nodekey=C:\Users\Heitor\ether-full\data-private\geth\nodekey`


And then i got
  👑 Welcome to the demo vipnode pool! 👑

awesome !

Where do i go from here ?

**Comment by shazow** [comment]
> Where do i go from here ?

You're good! Your node is ready to serve light clients and earn some sweet fake testnet money. :)

You should see your node here: https://vipnode.org/status/

**Comment by heitorfm** [comment]
Niiice, niiice,

Some questions:

Looks like the '--payout' flag is been ignored. Right ?

Me server is showing with 'd1ea652fa540… running geth at block 0.'
This means that my ether node is out of sync ?

I want to contribute to the project, are there spots available? I was thinking in improve the docs at first. What do you think ?

Thank you

**Comment by shazow** [comment]
Er if you're running a host (full node), you need to do `vipnode.exe host ...`, the payout flag is for that. Do --help to get all the flags. Sorry I'm traveling right now so responses are on my phone. :)

I very much appreciate contributions. Doc's are always great, I'd appreciate a guide for Windows since I don't have a Windows machine and that would be useful. Could put it on the wiki or as a .md in the repo.

What other kinds of things are you into? I can make some suggestions.
